# James Wilcox, Silly Sentences Python

name = input("Give me a name: ").strip().capitalize()
print(name)
color = input("Name a color: ")
print(color)
texture = input("Input a texture: ")
print(texture)
toy = input("name one toy: ")
print(toy)
flavor = input("Name a flavor: ")
print(flavor)
transportation = input("What is a type of transportation: ")
print(transportation)
print(f"You and your friend, {name}, go out to play in the beautiful {color} grass, but on the way, you find stinky Joe playing by himself in the sewers, drinking {flavor} flavored {texture} water from the ceiling. You and {name} shudder and continue to find the coveted {toy}. After a while, you get tired of walking and see an old man riding an old {transportation}. You and {name} beat him up, take his {transportation}, and go home.")