# James Wilcox, Silly Sentences Python

name = input("Give me a name: ")
print(name)
color = input("Name a color: ")
print(color)
texture = input("Input a texture: ")
print(texture)
toy = input("name one toy: ")
print(toy)
flavor = input("Name a flavor: ")
print(flavor)
transportation = input("Input a type of transportation: ")
print(transportation)
print("You and your friend, {name}, go out to play in the beautiful {color} grass. ")